### ISSUE TITLE
Noe galt med vårt sertifikat?

### ISSUE THREAD

**Issue by arnfinn** [mong/mong#12]
Jeg kommer meg ikke inn på skde.no med firefox på helse-nord-maskin.

![image](https://user-images.githubusercontent.com/136346/140313709-2af9f640-1d7c-49dd-9f16-377bc4d4ea06.png)

![image](https://user-images.githubusercontent.com/136346/140313809-c7fde52a-0541-45e8-b38e-6acbba1029dd.png)

```
Error code: SEC_ERROR_UNKNOWN_ISSUER
```

**Comment by areedv** [comment]
Sertifikatet til skde.no er gyldig og jeg klarer ikke gjenskape feilen (i crome) når jeg er innlogget gjennom portalen. Akkurat her  skjer det nok noe i brannmuren til helse nord (se "Verified by:" men at utløpsdatoen er riktig). Om dette er et faktisk problem (og ikke bare et isolert tilfelle) kan det tenkes at dette hører hjemme hos brukerstøtte i hn

I skjermdumpen under ser det ut til at brannmuren faktisk har klart å videreformidle riktig sertifikat (men satt seg selv som utsteder):
![image](https://user-images.githubusercontent.com/1522857/140325312-3597cb43-86d6-41de-bd66-d43ebca835df.png)

**Comment by rogereriksen** [comment]
Er det noen omdirigering av skde.no på det interne nettet fortsatt?

**Comment by rogereriksen** [comment]
Jeg klarer heller ikke å gjenskape feilen. Jeg har testet via Citrix og får ikke feilen. Heller ikke fra et eksternt nett får jeg feilen.

**Comment by areedv** [comment]
> Er det noen omdirigering av skde.no på det interne nettet fortsatt?

Nei, men jeg tror hn sin proxy/brannmur pakker ut ssl før den videresender og jeg antar at en feil i denne prosessen er årsaken feilen som @arnfinn ser. Sikkert lurt finne navnet på proxyen som ligger bak feilen (eksempelvis www-proxy2 slik som det fremgår av min skjermdump)

**Comment by arnfinn** [comment]
> Jeg klarer heller ikke å gjenskape feilen. Jeg har testet via Citrix og får ikke feilen. Heller ikke fra et eksternt nett får jeg feilen.

Med Firefox? Chrome fungerer fint.

**Comment by areedv** [comment]
Ingen brannrev i portalen, så det får jeg ikke prøvd... Tilbys firefox som en nettleser på hn-maskiner?

**Comment by arnfinn** [comment]
Firefox tilbys ikke direkte. Måtte installeres "for hånd" av en med admin-rettigheter. Så sikkert ikke et utbredt problem.

**Comment by areedv** [comment]
Da tror jeg vi lukker denne. Om samme problem oppstår i chrome eller exploder (Gud forby) så kan vi gjenåpne saken og forsøke lykken hos brukerstøtte i første omgang.
