### ISSUE TITLE
Se på tilsvarende/alternativ/komplementerende verktøy til Sentry

### ISSUE THREAD

**Issue by gabriofr** [mong/mong#2]
Dere må ta en avgjørelse på om vi skal ta i bruk sentry eller ikke. 

Vi anbefaler det, den har en tett integrasjon mot github  der vi vil få info om hvilke commits og releases som antagelig førte til exception, i tillegg er issue integrasjonen to-veis og håndtert veldig ryddig mellom systemene.
Vi tenker at dette kan være nyttig å ha i tillegg til mer bruksmønster analyseverktøy.

Dere må også ta prisen med i betraktning når dere vurderer : https://sentry.io/pricing/

Jeg setter [qmongjs#89](https://github.com/mong/qmongjs/issues/89) til blocked inntil beslutning er tatt :)

**Comment by areedv** [comment]
Jeg har ikke grunnlag for å mene noe om muligheter og begrensninger ved sentry, så der hører jeg heller på den anbefalingen som blir gitt. Antar videre at "Team" er riktig nivå for oss og det klarer vi fint å betale. Skal jeg opprette en konto?

**Comment by gabriofr** [comment]
> Jeg har ikke grunnlag for å mene noe om muligheter og begrensninger ved sentry, så der hører jeg heller på den anbefalingen som blir gitt. Antar videre at "Team" er riktig nivå for oss og det klarer vi fint å betale. Skal jeg opprette en konto?

Veldig gjerne :)

**Comment by gabriofr** [comment]
@areedv inviterer du gabrio@jupiter.no til sentry når dere har opprettet konto?

**Comment by areedv** [comment]
Sånn, @gabriofr, da skal det være sendt en invitasjon

**Comment by arnfinn** [comment]
Vi prøver Sentry.
