### ISSUE TITLE
Dropp dynamisk IP for beanstalk.

### ISSUE THREAD

**Issue by arnfinn** [mong/mong#7]
Oppdateringer feiler fordi vi har brukt opp de fem vi kan bruke.

Oppdatering feiler pga dette.

```
Creating EIP failed Reason: The maximum number of addresses has been reached. (Service: AmazonEC2; Status Code: 400; Error Code: AddressLimitExceeded; Request ID: <blablabla>; Proxy: null)
```

**Comment by LarsJK** [comment]
Måtte bruke "load balanced" istedet for "single instance" siden beanstalk fjerner og setter opp nye instanser. Load balanceren får da IPen og vil ikke tas ned ved ny deploy.
